apiVersion: v2
name: pagopareceiptpdfnotifier
description: Microservice description
type: application
version: 0.98.0
appVersion: 0.13.6-1-PRDP-61-refactor-io-client
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
