apiVersion: v2
name: pagopareceiptpdfnotifier
description: Microservice description
type: application
version: 0.102.0
appVersion: 0.13.7-1-PAGOPA-3372-cart-receipt-notifier-function
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
