apiVersion: v2
name: pagopareceiptpdfnotifier
description: Microservice description
type: application
version: 0.107.0
appVersion: 0.15.0-1-PAGOPA-3426-add-remote-content
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
