apiVersion: v2
name: pagopareceiptpdfnotifier
description: Microservice description
type: application
version: 0.96.0
appVersion: 0.13.5
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
