apiVersion: v2
name: pagopareceiptpdfnotifier
description: Microservice description
type: application
version: 0.109.0
appVersion: 0.15.1-1-PAGOPA-3396-integrates-new-cart-message-template
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
