apiVersion: v2
name: pagopareceiptpdfnotifier
description: Microservice description
type: application
version: 0.101.0
appVersion: 0.13.7
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
