apiVersion: v2
name: pagopareceiptpdfnotifier
description: Microservice description
type: application
version: 0.108.0
appVersion: 0.15.1
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
