apiVersion: v2
name: pagopareceiptpdfnotifier
description: Microservice description
type: application
version: 0.105.0
appVersion: 0.14.0-7-PAGOPA-3373
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
