apiVersion: v2
name: pagopareceiptpdfnotifier
description: Microservice description
type: application
version: 0.115.0
appVersion: 0.15.4-1-rename-cart-id
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
