apiVersion: v2
name: pagopareceiptpdfnotifier
description: Microservice description
type: application
version: 0.104.0
appVersion: 0.14.0
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
